name: Build Engine

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04 [Beta]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Install dependencies
        run: |
          sudo brew update
          sudo brew install -y ninja-build
          chmod +x setup.sh
          ./setup.sh
      - name: Build
        run: ./build.sh
